stages:
  download_data:
    foreach: # List of simple values
      - WDI_csv.zip
      - Gender_Stats_csv.zip 
      - IDS_CSV.zip
    do:
      cmd: wget "https://databank.worldbank.org/data/download/${item}" -O "data/raw/${item}"
      outs:
        - data/raw/${item}

  process_data:
    cmd: python src/process.py
    deps:
    - config/main.yaml
    - config/process
    - data/raw
    - src/process.py
    outs:
    - data/processed:
        persist: true

  train_model:
    cmd: python src/train_model.py
    deps:
    - config/main.yaml
    - config/model
    - data/processed
    - src/train_model.py
    outs:
    - data/final:
        persist: true
    - models:
        persist: true

