stages:
  download_data:
    cmd:  wget https://databank.worldbank.org/data/download/WDI_csv.zip -O data/raw/WDI_csv.zip; \\
          wget https://databank.worldbank.org/data/download/Gender_Stats_csv.zip -O data/raw/WDI_csv.zip; \\
          wget https://databank.worldbank.org/data/download/IDS_CSV.zip; \\
    deps:
    - https://databank.worldbank.org/data/download/WDI_csv.zip
    - https://databank.worldbank.org/data/download/Gender_Stats_csv.zip
    - https://databank.worldbank.org/data/download/IDS_CSV.zip
    outs:
    - data/raw/WDI_csv.zip
    - data/raw/Gender_Stats_csv.zip
    - data/raw/IDS_CSV.zip

  process_data:
    cmd: python src/process.py
    deps:
    - config/main.yaml
    - config/process
    - data/raw
    - src/process.py
    outs:
    - data/processed:
        persist: true

  train_model:
    cmd: python src/train_model.py
    deps:
    - config/main.yaml
    - config/model
    - data/processed
    - src/train_model.py
    outs:
    - data/final:
        persist: true
    - models:
        persist: true

